/*
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SimpleProject'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SimpleProject'));
  } else {
    // Browser globals (root is window)
    if (!root.LoaderoController) {
      root.LoaderoController = {};
    }
    root.LoaderoController.AwsInfoReponse = factory(root.LoaderoController.ApiClient, root.LoaderoController.SimpleProject);
  }
}(this, function(ApiClient, SimpleProject) {
  'use strict';

  /**
   * The AwsInfoReponse model module.
   * @module model/AwsInfoReponse
   * @version v0.32.1
   */

  /**
   * Constructs a new <code>AwsInfoReponse</code>.
   * AWSInfoReponse is response format that contains linked projects info and AWSInfo corresponding to query.
   * @alias module:model/AwsInfoReponse
   * @class
   * @param accountId {String} 
   * @param clientId {String} 
   */
  var exports = function(accountId, clientId) {
    this.accountId = accountId;
    this.clientId = clientId;
  };

  /**
   * Constructs a <code>AwsInfoReponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AwsInfoReponse} obj Optional instance to populate.
   * @return {module:model/AwsInfoReponse} The populated <code>AwsInfoReponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('account_id'))
        obj.accountId = ApiClient.convertToType(data['account_id'], 'String');
      if (data.hasOwnProperty('artifact_bucket'))
        obj.artifactBucket = ApiClient.convertToType(data['artifact_bucket'], 'String');
      if (data.hasOwnProperty('client_id'))
        obj.clientId = ApiClient.convertToType(data['client_id'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('linked_projects'))
        obj.linkedProjects = ApiClient.convertToType(data['linked_projects'], [SimpleProject]);
      if (data.hasOwnProperty('log_bucket'))
        obj.logBucket = ApiClient.convertToType(data['log_bucket'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
    }
    return obj;
  }

  /**
   * @member {String} accountId
   */
  exports.prototype.accountId = undefined;

  /**
   * @member {String} artifactBucket
   */
  exports.prototype.artifactBucket = undefined;

  /**
   * @member {String} clientId
   */
  exports.prototype.clientId = undefined;

  /**
   * @member {Date} created
   */
  exports.prototype.created = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {Array.<module:model/SimpleProject>} linkedProjects
   */
  exports.prototype.linkedProjects = undefined;

  /**
   * @member {String} logBucket
   */
  exports.prototype.logBucket = undefined;

  /**
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {Date} updated
   */
  exports.prototype.updated = undefined;


  return exports;

}));
