/*
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AssertOverview} from './AssertOverview';
import {MachineStats} from './MachineStats';

/**
 * The InlineResponse2003 model module.
 * @module model/InlineResponse2003
 * @version v0.32.1
 */
export class InlineResponse2003 {
  /**
   * Constructs a new <code>InlineResponse2003</code>.
   * @alias module:model/InlineResponse2003
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2003</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2003} obj Optional instance to populate.
   * @return {module:model/InlineResponse2003} The populated <code>InlineResponse2003</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2003();
      if (data.hasOwnProperty('asserts'))
        obj.asserts = ApiClient.convertToType(data['asserts'], [AssertOverview]);
      if (data.hasOwnProperty('machine_stats'))
        obj.machineStats = MachineStats.constructFromObject(data['machine_stats']);
    }
    return obj;
  }
}

/**
 * @member {Array.<module:model/AssertOverview>} asserts
 */
InlineResponse2003.prototype.asserts = undefined;

/**
 * @member {module:model/MachineStats} machineStats
 */
InlineResponse2003.prototype.machineStats = undefined;

