/*
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Statistics} from './Statistics';

/**
 * The MachineStats model module.
 * @module model/MachineStats
 * @version v0.32.1
 */
export class MachineStats {
  /**
   * Constructs a new <code>MachineStats</code>.
   * MachineStats consists of indicators about resource usage by the test execution.
   * @alias module:model/MachineStats
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MachineStats</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MachineStats} obj Optional instance to populate.
   * @return {module:model/MachineStats} The populated <code>MachineStats</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MachineStats();
      if (data.hasOwnProperty('avg'))
        obj.avg = Statistics.constructFromObject(data['avg']);
      if (data.hasOwnProperty('max'))
        obj.max = Statistics.constructFromObject(data['max']);
      if (data.hasOwnProperty('min'))
        obj.min = Statistics.constructFromObject(data['min']);
      if (data.hasOwnProperty('perc_25'))
        obj.perc25 = Statistics.constructFromObject(data['perc_25']);
      if (data.hasOwnProperty('perc_50'))
        obj.perc50 = Statistics.constructFromObject(data['perc_50']);
      if (data.hasOwnProperty('perc_75'))
        obj.perc75 = Statistics.constructFromObject(data['perc_75']);
      if (data.hasOwnProperty('perc_95'))
        obj.perc95 = Statistics.constructFromObject(data['perc_95']);
      if (data.hasOwnProperty('perc_99'))
        obj.perc99 = Statistics.constructFromObject(data['perc_99']);
      if (data.hasOwnProperty('relative_std_dev'))
        obj.relativeStdDev = Statistics.constructFromObject(data['relative_std_dev']);
      if (data.hasOwnProperty('std_dev'))
        obj.stdDev = Statistics.constructFromObject(data['std_dev']);
      if (data.hasOwnProperty('total'))
        obj.total = Statistics.constructFromObject(data['total']);
    }
    return obj;
  }
}

/**
 * @member {module:model/Statistics} avg
 */
MachineStats.prototype.avg = undefined;

/**
 * @member {module:model/Statistics} max
 */
MachineStats.prototype.max = undefined;

/**
 * @member {module:model/Statistics} min
 */
MachineStats.prototype.min = undefined;

/**
 * @member {module:model/Statistics} perc25
 */
MachineStats.prototype.perc25 = undefined;

/**
 * @member {module:model/Statistics} perc50
 */
MachineStats.prototype.perc50 = undefined;

/**
 * @member {module:model/Statistics} perc75
 */
MachineStats.prototype.perc75 = undefined;

/**
 * @member {module:model/Statistics} perc95
 */
MachineStats.prototype.perc95 = undefined;

/**
 * @member {module:model/Statistics} perc99
 */
MachineStats.prototype.perc99 = undefined;

/**
 * @member {module:model/Statistics} relativeStdDev
 */
MachineStats.prototype.relativeStdDev = undefined;

/**
 * @member {module:model/Statistics} stdDev
 */
MachineStats.prototype.stdDev = undefined;

/**
 * @member {module:model/Statistics} total
 */
MachineStats.prototype.total = undefined;

