/*
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Params model module.
 * @module model/Params
 * @version v0.32.1
 */
export class Params {
  /**
   * Constructs a new <code>Params</code>.
   * @alias module:model/Params
   * @class
   * @param browser {String} 
   */
  constructor(browser) {
    this.browser = browser;
  }

  /**
   * Constructs a <code>Params</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Params} obj Optional instance to populate.
   * @return {module:model/Params} The populated <code>Params</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Params();
      if (data.hasOwnProperty('audio_feed'))
        obj.audioFeed = ApiClient.convertToType(data['audio_feed'], 'String');
      if (data.hasOwnProperty('browser'))
        obj.browser = ApiClient.convertToType(data['browser'], 'String');
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('media_type'))
        obj.mediaType = ApiClient.convertToType(data['media_type'], 'String');
      if (data.hasOwnProperty('network'))
        obj.network = ApiClient.convertToType(data['network'], 'String');
      if (data.hasOwnProperty('video_feed'))
        obj.videoFeed = ApiClient.convertToType(data['video_feed'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} audioFeed
 */
Params.prototype.audioFeed = undefined;

/**
 * @member {String} browser
 */
Params.prototype.browser = undefined;

/**
 * @member {String} location
 */
Params.prototype.location = undefined;

/**
 * @member {String} mediaType
 */
Params.prototype.mediaType = undefined;

/**
 * @member {String} network
 */
Params.prototype.network = undefined;

/**
 * @member {String} videoFeed
 */
Params.prototype.videoFeed = undefined;

