/*
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Project model module.
 * @module model/Project
 * @version v0.32.1
 */
export class Project {
  /**
   * Constructs a new <code>Project</code>.
   * @alias module:model/Project
   * @class
   * @param language {String} 
   * @param name {String} 
   */
  constructor(language, name) {
    this.language = language;
    this.name = name;
  }

  /**
   * Constructs a <code>Project</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Project} obj Optional instance to populate.
   * @return {module:model/Project} The populated <code>Project</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Project();
      if (data.hasOwnProperty('account_role'))
        obj.accountRole = ApiClient.convertToType(data['account_role'], 'String');
      if (data.hasOwnProperty('aws_info_id'))
        obj.awsInfoId = ApiClient.convertToType(data['aws_info_id'], 'Number');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('member_count'))
        obj.memberCount = ApiClient.convertToType(data['member_count'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('subscription_id'))
        obj.subscriptionId = ApiClient.convertToType(data['subscription_id'], 'Number');
      if (data.hasOwnProperty('trial_expired'))
        obj.trialExpired = ApiClient.convertToType(data['trial_expired'], 'Boolean');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} accountRole
 */
Project.prototype.accountRole = undefined;

/**
 * @member {Number} awsInfoId
 */
Project.prototype.awsInfoId = undefined;

/**
 * @member {Date} created
 */
Project.prototype.created = undefined;

/**
 * @member {Number} id
 */
Project.prototype.id = undefined;

/**
 * @member {String} language
 */
Project.prototype.language = undefined;

/**
 * @member {Number} memberCount
 */
Project.prototype.memberCount = undefined;

/**
 * @member {String} name
 */
Project.prototype.name = undefined;

/**
 * @member {Number} subscriptionId
 */
Project.prototype.subscriptionId = undefined;

/**
 * @member {Boolean} trialExpired
 */
Project.prototype.trialExpired = undefined;

/**
 * @member {Date} updated
 */
Project.prototype.updated = undefined;

