/*
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ResultLog model module.
 * @module model/ResultLog
 * @version v0.32.1
 */
export class ResultLog {
  /**
   * Constructs a new <code>ResultLog</code>.
   * @alias module:model/ResultLog
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ResultLog</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ResultLog} obj Optional instance to populate.
   * @return {module:model/ResultLog} The populated <code>ResultLog</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ResultLog();
      if (data.hasOwnProperty('browser'))
        obj.browser = ApiClient.convertToType(data['browser'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('result_id'))
        obj.resultId = ApiClient.convertToType(data['result_id'], 'Number');
      if (data.hasOwnProperty('rru'))
        obj.rru = ApiClient.convertToType(data['rru'], 'String');
      if (data.hasOwnProperty('selenium'))
        obj.selenium = ApiClient.convertToType(data['selenium'], 'String');
      if (data.hasOwnProperty('webrtc'))
        obj.webrtc = ApiClient.convertToType(data['webrtc'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} browser
 */
ResultLog.prototype.browser = undefined;

/**
 * @member {Date} created
 */
ResultLog.prototype.created = undefined;

/**
 * @member {Number} id
 */
ResultLog.prototype.id = undefined;

/**
 * @member {Number} resultId
 */
ResultLog.prototype.resultId = undefined;

/**
 * @member {String} rru
 */
ResultLog.prototype.rru = undefined;

/**
 * @member {String} selenium
 */
ResultLog.prototype.selenium = undefined;

/**
 * @member {String} webrtc
 */
ResultLog.prototype.webrtc = undefined;

