/*
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RunParticipant model module.
 * @module model/RunParticipant
 * @version v0.32.1
 */
export class RunParticipant {
  /**
   * Constructs a new <code>RunParticipant</code>.
   * RunParticipant describes single run participant instance with JSON field descriptions. swagger: model
   * @alias module:model/RunParticipant
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RunParticipant</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RunParticipant} obj Optional instance to populate.
   * @return {module:model/RunParticipant} The populated <code>RunParticipant</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RunParticipant();
      if (data.hasOwnProperty('compute_unit'))
        obj.computeUnit = ApiClient.convertToType(data['compute_unit'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('group_name'))
        obj.groupName = ApiClient.convertToType(data['group_name'], 'String');
      if (data.hasOwnProperty('group_num'))
        obj.groupNum = ApiClient.convertToType(data['group_num'], 'Number');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('participant_name'))
        obj.participantName = ApiClient.convertToType(data['participant_name'], 'String');
      if (data.hasOwnProperty('participant_num'))
        obj.participantNum = ApiClient.convertToType(data['participant_num'], 'Number');
      if (data.hasOwnProperty('profile_id'))
        obj.profileId = ApiClient.convertToType(data['profile_id'], 'Number');
      if (data.hasOwnProperty('record_audio'))
        obj.recordAudio = ApiClient.convertToType(data['record_audio'], 'Boolean');
      if (data.hasOwnProperty('run_id'))
        obj.runId = ApiClient.convertToType(data['run_id'], 'Number');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} computeUnit
 */
RunParticipant.prototype.computeUnit = undefined;

/**
 * @member {Date} created
 */
RunParticipant.prototype.created = undefined;

/**
 * @member {String} groupName
 */
RunParticipant.prototype.groupName = undefined;

/**
 * @member {Number} groupNum
 */
RunParticipant.prototype.groupNum = undefined;

/**
 * @member {Number} id
 */
RunParticipant.prototype.id = undefined;

/**
 * @member {String} participantName
 */
RunParticipant.prototype.participantName = undefined;

/**
 * @member {Number} participantNum
 */
RunParticipant.prototype.participantNum = undefined;

/**
 * @member {Number} profileId
 */
RunParticipant.prototype.profileId = undefined;

/**
 * @member {Boolean} recordAudio
 */
RunParticipant.prototype.recordAudio = undefined;

/**
 * @member {Number} runId
 */
RunParticipant.prototype.runId = undefined;

/**
 * @member {Date} updated
 */
RunParticipant.prototype.updated = undefined;

