/*
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.LoaderoController) {
      root.LoaderoController = {};
    }
    root.LoaderoController.RunParticipantBody = factory(root.LoaderoController.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The RunParticipantBody model module.
   * @module model/RunParticipantBody
   * @version v0.32.1
   */

  /**
   * Constructs a new <code>RunParticipantBody</code>.
   * Body describes single run participant instance with JSON field descriptions.
   * @alias module:model/RunParticipantBody
   * @class
   * @param browser {String} 
   */
  var exports = function(browser) {
    this.browser = browser;
  };

  /**
   * Constructs a <code>RunParticipantBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RunParticipantBody} obj Optional instance to populate.
   * @return {module:model/RunParticipantBody} The populated <code>RunParticipantBody</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('audio_feed'))
        obj.audioFeed = ApiClient.convertToType(data['audio_feed'], 'String');
      if (data.hasOwnProperty('browser'))
        obj.browser = ApiClient.convertToType(data['browser'], 'String');
      if (data.hasOwnProperty('compute_unit'))
        obj.computeUnit = ApiClient.convertToType(data['compute_unit'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('group_name'))
        obj.groupName = ApiClient.convertToType(data['group_name'], 'String');
      if (data.hasOwnProperty('group_num'))
        obj.groupNum = ApiClient.convertToType(data['group_num'], 'Number');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('media_type'))
        obj.mediaType = ApiClient.convertToType(data['media_type'], 'String');
      if (data.hasOwnProperty('network'))
        obj.network = ApiClient.convertToType(data['network'], 'String');
      if (data.hasOwnProperty('participant_name'))
        obj.participantName = ApiClient.convertToType(data['participant_name'], 'String');
      if (data.hasOwnProperty('participant_num'))
        obj.participantNum = ApiClient.convertToType(data['participant_num'], 'Number');
      if (data.hasOwnProperty('profile_id'))
        obj.profileId = ApiClient.convertToType(data['profile_id'], 'Number');
      if (data.hasOwnProperty('record_audio'))
        obj.recordAudio = ApiClient.convertToType(data['record_audio'], 'Boolean');
      if (data.hasOwnProperty('run_id'))
        obj.runId = ApiClient.convertToType(data['run_id'], 'Number');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('video_feed'))
        obj.videoFeed = ApiClient.convertToType(data['video_feed'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} audioFeed
   */
  exports.prototype.audioFeed = undefined;

  /**
   * @member {String} browser
   */
  exports.prototype.browser = undefined;

  /**
   * @member {String} computeUnit
   */
  exports.prototype.computeUnit = undefined;

  /**
   * @member {Date} created
   */
  exports.prototype.created = undefined;

  /**
   * @member {String} groupName
   */
  exports.prototype.groupName = undefined;

  /**
   * @member {Number} groupNum
   */
  exports.prototype.groupNum = undefined;

  /**
   * @member {Number} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} location
   */
  exports.prototype.location = undefined;

  /**
   * @member {String} mediaType
   */
  exports.prototype.mediaType = undefined;

  /**
   * @member {String} network
   */
  exports.prototype.network = undefined;

  /**
   * @member {String} participantName
   */
  exports.prototype.participantName = undefined;

  /**
   * @member {Number} participantNum
   */
  exports.prototype.participantNum = undefined;

  /**
   * @member {Number} profileId
   */
  exports.prototype.profileId = undefined;

  /**
   * @member {Boolean} recordAudio
   */
  exports.prototype.recordAudio = undefined;

  /**
   * @member {Number} runId
   */
  exports.prototype.runId = undefined;

  /**
   * @member {Date} updated
   */
  exports.prototype.updated = undefined;

  /**
   * @member {String} videoFeed
   */
  exports.prototype.videoFeed = undefined;


  return exports;

}));
