/*
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ClassificatorType} from './ClassificatorType';

/**
 * The TestMode model module.
 * @module model/TestMode
 * @version v0.32.1
 */
export class TestMode {
  /**
   * Constructs a new <code>TestMode</code>.
   * TestMode is a concrete classificator value that is used to describe different test mode values. Test mode determines different logical parts of the test such as log collection logic and different service limits.
   * @alias module:model/TestMode
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TestMode</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TestMode} obj Optional instance to populate.
   * @return {module:model/TestMode} The populated <code>TestMode</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TestMode();
      if (data.hasOwnProperty('classificator'))
        obj.classificator = ClassificatorType.constructFromObject(data['classificator']);
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('disabled'))
        obj.disabled = ApiClient.convertToType(data['disabled'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('value'))
        obj.value = ApiClient.convertToType(data['value'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/ClassificatorType} classificator
 */
TestMode.prototype.classificator = undefined;

/**
 * @member {String} description
 */
TestMode.prototype.description = undefined;

/**
 * @member {Boolean} disabled
 */
TestMode.prototype.disabled = undefined;

/**
 * @member {String} name
 */
TestMode.prototype.name = undefined;

/**
 * @member {String} value
 */
TestMode.prototype.value = undefined;

