/*
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoaderoController);
  }
}(this, function(expect, LoaderoController) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoaderoController.GroupApi();
  });

  describe('(package)', function() {
    describe('GroupApi', function() {
      describe('createGroup', function() {
        it('should call createGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for createGroup call and complete the assertions
          /*
          var projectID = 789;
          var testID = 789;
          var opts = {};
          opts.describe = "describe_example";
          opts.group = new LoaderoController.Group();
          opts.group.count = "0";
          opts.group.name = "";

          instance.createGroup(projectID, testID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LoaderoController.Group);
            expect(data.count).to.be.a('number');
            expect(data.count).to.be("0");
            expect(data.created).to.be.a(Date);
            expect(data.created).to.be(new Date());
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.participantCount).to.be.a('number');
            expect(data.participantCount).to.be("0");
            expect(data.testId).to.be.a('number');
            expect(data.testId).to.be("0");
            expect(data.updated).to.be.a(Date);
            expect(data.updated).to.be(new Date());

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteGroup', function() {
        it('should call deleteGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteGroup call
          /*
          var groupID = 789;
          var projectID = 789;
          var testID = 789;

          instance.deleteGroup(groupID, projectID, testID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('duplicateGroup', function() {
        it('should call duplicateGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for duplicateGroup call and complete the assertions
          /*
          var groupID = 789;
          var projectID = 789;
          var testID = 789;
          var opts = {};
          opts.body = new LoaderoController.Body();
          opts.describe = "describe_example";

          instance.duplicateGroup(groupID, projectID, testID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LoaderoController.Group);
            expect(data.count).to.be.a('number');
            expect(data.count).to.be("0");
            expect(data.created).to.be.a(Date);
            expect(data.created).to.be(new Date());
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.participantCount).to.be.a('number');
            expect(data.participantCount).to.be("0");
            expect(data.testId).to.be.a('number');
            expect(data.testId).to.be("0");
            expect(data.updated).to.be.a(Date);
            expect(data.updated).to.be(new Date());

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readAllGroups', function() {
        it('should call readAllGroups successfully', function(done) {
          // TODO: uncomment, update parameter values for readAllGroups call and complete the assertions
          /*
          var projectID = 789;
          var testID = 789;
          var opts = {};
          opts.limit = 789;
          opts.offset = 789;
          opts.describe = "describe_example";
          opts.filterName = "filterName_example";
          opts.filterCountFrom = "filterCountFrom_example";
          opts.filterCountTo = "filterCountTo_example";

          instance.readAllGroups(projectID, testID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readGroup', function() {
        it('should call readGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for readGroup call and complete the assertions
          /*
          var groupID = 789;
          var projectID = 789;
          var testID = 789;
          var opts = {};
          opts.describe = "describe_example";

          instance.readGroup(groupID, projectID, testID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LoaderoController.Group);
            expect(data.count).to.be.a('number');
            expect(data.count).to.be("0");
            expect(data.created).to.be.a(Date);
            expect(data.created).to.be(new Date());
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.participantCount).to.be.a('number');
            expect(data.participantCount).to.be("0");
            expect(data.testId).to.be.a('number');
            expect(data.testId).to.be("0");
            expect(data.updated).to.be.a(Date);
            expect(data.updated).to.be(new Date());

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateGroup', function() {
        it('should call updateGroup successfully', function(done) {
          // TODO: uncomment, update parameter values for updateGroup call and complete the assertions
          /*
          var groupID = 789;
          var projectID = 789;
          var testID = 789;
          var opts = {};
          opts.describe = "describe_example";
          opts.group = new LoaderoController.Group();
          opts.group.count = "0";
          opts.group.name = "";

          instance.updateGroup(groupID, projectID, testID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LoaderoController.Group);
            expect(data.count).to.be.a('number');
            expect(data.count).to.be("0");
            expect(data.created).to.be.a(Date);
            expect(data.created).to.be(new Date());
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.participantCount).to.be.a('number');
            expect(data.participantCount).to.be("0");
            expect(data.testId).to.be.a('number');
            expect(data.testId).to.be("0");
            expect(data.updated).to.be.a(Date);
            expect(data.updated).to.be(new Date());

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
