/*
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoaderoController);
  }
}(this, function(expect, LoaderoController) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoaderoController.ParticipantsApi();
  });

  describe('(package)', function() {
    describe('ParticipantsApi', function() {
      describe('createParticipant', function() {
        it('should call createParticipant successfully', function(done) {
          // TODO: uncomment, update parameter values for createParticipant call and complete the assertions
          /*
          var opts = {};

          instance.createParticipant(projectID, testID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LoaderoController.ParticipantBody);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteParticipant', function() {
        it('should call deleteParticipant successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteParticipant call
          /*

          instance.deleteParticipant(participantID, projectID, testID, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('duplicateParticipant', function() {
        it('should call duplicateParticipant successfully', function(done) {
          // TODO: uncomment, update parameter values for duplicateParticipant call and complete the assertions
          /*
          var opts = {};

          instance.duplicateParticipant(participantID, projectID, testID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LoaderoController.ParticipantBody);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readAllParticipants', function() {
        it('should call readAllParticipants successfully', function(done) {
          // TODO: uncomment, update parameter values for readAllParticipants call and complete the assertions
          /*
          var opts = {};

          instance.readAllParticipants(projectID, testID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LoaderoController.InlineResponse2008);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readParticipant', function() {
        it('should call readParticipant successfully', function(done) {
          // TODO: uncomment, update parameter values for readParticipant call and complete the assertions
          /*
          var opts = {};

          instance.readParticipant(participantID, projectID, testID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LoaderoController.ParticipantBody);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateParticipant', function() {
        it('should call updateParticipant successfully', function(done) {
          // TODO: uncomment, update parameter values for updateParticipant call and complete the assertions
          /*
          var opts = {};

          instance.updateParticipant(participantID, projectID, testID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LoaderoController.ParticipantBody);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
