/*
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoaderoController);
  }
}(this, function(expect, LoaderoController) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoaderoController.ProjectresultApi();
  });

  describe('(package)', function() {
    describe('ProjectresultApi', function() {
      describe('readAllProjectResults', function() {
        it('should call readAllProjectResults successfully', function(done) {
          // TODO: uncomment, update parameter values for readAllProjectResults call and complete the assertions
          /*
          var opts = {};

          instance.readAllProjectResults(runID, projectID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LoaderoController.InlineResponse2002);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readProjectResult', function() {
        it('should call readProjectResult successfully', function(done) {
          // TODO: uncomment, update parameter values for readProjectResult call and complete the assertions
          /*
          var opts = {};

          instance.readProjectResult(resultID, runID, projectID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LoaderoController.ExtendedResult);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readProjectResultStatistics', function() {
        it('should call readProjectResultStatistics successfully', function(done) {
          // TODO: uncomment, update parameter values for readProjectResultStatistics call and complete the assertions
          /*
          var opts = {};

          instance.readProjectResultStatistics(runID, projectID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LoaderoController.InlineResponse2003);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
