/*
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.21
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.LoaderoController);
  }
}(this, function(expect, LoaderoController) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new LoaderoController.RunparticipantApi();
  });

  describe('(package)', function() {
    describe('RunparticipantApi', function() {
      describe('readAllTestRunParticipants', function() {
        it('should call readAllTestRunParticipants successfully', function(done) {
          // TODO: uncomment, update parameter values for readAllTestRunParticipants call and complete the assertions
          /*
          var runID = 789;
          var testID = 789;
          var projectID = 789;
          var opts = {};
          opts.limit = 789;
          opts.offset = 789;
          opts.describe = "describe_example";
          opts.filterBrowser = "filterBrowser_example";
          opts.filterNetwork = "filterNetwork_example";
          opts.filterLocation = "filterLocation_example";
          opts.filterMediaType = "filterMediaType_example";
          opts.filterVideoFeed = "filterVideoFeed_example";
          opts.filterAudioFeed = "filterAudioFeed_example";
          opts.filterName = "filterName_example";
          opts.filterNumFrom = "filterNumFrom_example";
          opts.filterNumTo = "filterNumTo_example";
          opts.filterGroupName = "filterGroupName_example";
          opts.filterGroupNumFrom = "filterGroupNumFrom_example";
          opts.filterGroupNumTo = "filterGroupNumTo_example";
          opts.filterRecordAudio = "filterRecordAudio_example";

          instance.readAllTestRunParticipants(runID, testID, projectID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Object);
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('readTestRunParticipant', function() {
        it('should call readTestRunParticipant successfully', function(done) {
          // TODO: uncomment, update parameter values for readTestRunParticipant call and complete the assertions
          /*
          var runParticipantID = 789;
          var runID = 789;
          var testID = 789;
          var projectID = 789;
          var opts = {};
          opts.describe = "describe_example";

          instance.readTestRunParticipant(runParticipantID, runID, testID, projectID, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(LoaderoController.RunParticipantBody);
            expect(data.audioFeed).to.be.a('string');
            expect(data.audioFeed).to.be("");
            expect(data.browser).to.be.a('string');
            expect(data.browser).to.be("");
            expect(data.computeUnit).to.be.a('string');
            expect(data.computeUnit).to.be("");
            expect(data.created).to.be.a(Date);
            expect(data.created).to.be(new Date());
            expect(data.groupName).to.be.a('string');
            expect(data.groupName).to.be("");
            expect(data.groupNum).to.be.a('number');
            expect(data.groupNum).to.be("0");
            expect(data.id).to.be.a('number');
            expect(data.id).to.be("0");
            expect(data.location).to.be.a('string');
            expect(data.location).to.be("");
            expect(data.mediaType).to.be.a('string');
            expect(data.mediaType).to.be("");
            expect(data.network).to.be.a('string');
            expect(data.network).to.be("");
            expect(data.participantName).to.be.a('string');
            expect(data.participantName).to.be("");
            expect(data.participantNum).to.be.a('number');
            expect(data.participantNum).to.be("0");
            expect(data.profileId).to.be.a('number');
            expect(data.profileId).to.be("0");
            expect(data.recordAudio).to.be.a('boolean');
            expect(data.recordAudio).to.be(false);
            expect(data.runId).to.be.a('number');
            expect(data.runId).to.be("0");
            expect(data.updated).to.be.a(Date);
            expect(data.updated).to.be(new Date());
            expect(data.videoFeed).to.be.a('string');
            expect(data.videoFeed).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
