/* tslint:disable */
/* eslint-disable */
/**
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * ArtifactsInfo contains all artifact URLs from single result for each corresponding artifact type. If error was present for a artifact type then URL paths for that artifact will be empty.
 * @export
 * @interface ArtifactsInfo
 */
export interface ArtifactsInfo {
    /**
     * 
     * @type {ArtifactInfo}
     * @memberof ArtifactsInfo
     */
    audio?: any;
    /**
     * 
     * @type {ArtifactInfo}
     * @memberof ArtifactsInfo
     */
    downloads?: any;
    /**
     * 
     * @type {ArtifactInfo}
     * @memberof ArtifactsInfo
     */
    screenshots?: any;
    /**
     * 
     * @type {ArtifactInfo}
     * @memberof ArtifactsInfo
     */
    video?: any;
}
