/* tslint:disable */
/* eslint-disable */
/**
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * AudioFeed is a concrete classificator value that is used to describe different audio feed values. Audio feed indicates the currently supported audio values.
 * @export
 * @interface AudioFeed
 */
export interface AudioFeed {
    /**
     * 
     * @type {ClassificatorType}
     * @memberof AudioFeed
     */
    classificator?: any;
    /**
     * 
     * @type {string}
     * @memberof AudioFeed
     */
    description?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AudioFeed
     */
    disabled?: any;
    /**
     * 
     * @type {string}
     * @memberof AudioFeed
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof AudioFeed
     */
    value?: any;
}
