/* tslint:disable */
/* eslint-disable */
/**
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * AWSInfoReponse is response format that contains linked projects info and AWSInfo corresponding to query.
 * @export
 * @interface AwsInfoReponse
 */
export interface AwsInfoReponse {
    /**
     * 
     * @type {string}
     * @memberof AwsInfoReponse
     */
    accountId: any;
    /**
     * 
     * @type {string}
     * @memberof AwsInfoReponse
     */
    artifactBucket?: any;
    /**
     * 
     * @type {string}
     * @memberof AwsInfoReponse
     */
    clientId: any;
    /**
     * 
     * @type {Date}
     * @memberof AwsInfoReponse
     */
    created?: any;
    /**
     * 
     * @type {number}
     * @memberof AwsInfoReponse
     */
    id?: any;
    /**
     * 
     * @type {Array&lt;SimpleProject&gt;}
     * @memberof AwsInfoReponse
     */
    linkedProjects?: any;
    /**
     * 
     * @type {string}
     * @memberof AwsInfoReponse
     */
    logBucket?: any;
    /**
     * 
     * @type {string}
     * @memberof AwsInfoReponse
     */
    status?: any;
    /**
     * 
     * @type {Date}
     * @memberof AwsInfoReponse
     */
    updated?: any;
}
