/* tslint:disable */
/* eslint-disable */
/**
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * BaseClassificator is exported wrapper for generic classificator type. This type should be used only to further extend capabilities of a classificator, and not used directly. In those cases prefer to use Classificator interface.
 * @export
 * @interface BaseClassificator
 */
export interface BaseClassificator {
    /**
     * 
     * @type {ClassificatorType}
     * @memberof BaseClassificator
     */
    classificator?: any;
    /**
     * 
     * @type {string}
     * @memberof BaseClassificator
     */
    description?: any;
    /**
     * 
     * @type {boolean}
     * @memberof BaseClassificator
     */
    disabled?: any;
    /**
     * 
     * @type {string}
     * @memberof BaseClassificator
     */
    name?: any;
    /**
     * 
     * @type {string}
     * @memberof BaseClassificator
     */
    value?: any;
}
