/* tslint:disable */
/* eslint-disable */
/**
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface FullAssert
 */
export interface FullAssert {
    /**
     * 
     * @type {Date}
     * @memberof FullAssert
     */
    created?: any;
    /**
     * 
     * @type {string}
     * @memberof FullAssert
     */
    expected: any;
    /**
     * 
     * @type {number}
     * @memberof FullAssert
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof FullAssert
     */
    operator: any;
    /**
     * 
     * @type {string}
     * @memberof FullAssert
     */
    path: any;
    /**
     * 
     * @type {Array&lt;AssertPrecondition&gt;}
     * @memberof FullAssert
     */
    preconditions?: any;
    /**
     * 
     * @type {number}
     * @memberof FullAssert
     */
    testId?: any;
    /**
     * 
     * @type {Date}
     * @memberof FullAssert
     */
    updated?: any;
}
