/* tslint:disable */
/* eslint-disable */
/**
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {
    /**
     * 
     * @type {Filterer}
     * @memberof InlineResponse2004
     */
    filter?: any;
    /**
     * 
     * @type {Pagination}
     * @memberof InlineResponse2004
     */
    pagination?: any;
    /**
     * 
     * @type {Array&lt;Test&gt;}
     * @memberof InlineResponse2004
     */
    results?: any;
}
