/* tslint:disable */
/* eslint-disable */
/**
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Metric
 */
export interface Metric {
    /**
     * 
     * @type {number}
     * @memberof Metric
     */
    average?: any;
    /**
     * 
     * @type {Date}
     * @memberof Metric
     */
    created?: any;
    /**
     * 
     * @type {number}
     * @memberof Metric
     */
    dataCount?: any;
    /**
     * 
     * @type {number}
     * @memberof Metric
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof Metric
     */
    maximum?: any;
    /**
     * 
     * @type {string}
     * @memberof Metric
     */
    metricPath: any;
    /**
     * 
     * @type {number}
     * @memberof Metric
     */
    minimum?: any;
    /**
     * 
     * @type {number}
     * @memberof Metric
     */
    perc25th?: any;
    /**
     * 
     * @type {number}
     * @memberof Metric
     */
    perc50th?: any;
    /**
     * 
     * @type {number}
     * @memberof Metric
     */
    perc75th?: any;
    /**
     * 
     * @type {number}
     * @memberof Metric
     */
    perc95th?: any;
    /**
     * 
     * @type {number}
     * @memberof Metric
     */
    perc99th?: any;
    /**
     * 
     * @type {number}
     * @memberof Metric
     */
    stddev?: any;
    /**
     * 
     * @type {string}
     * @memberof Metric
     */
    value?: any;
}
