/* tslint:disable */
/* eslint-disable */
/**
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface NetworkParams
 */
export interface NetworkParams {
    /**
     * 
     * @type {number}
     * @memberof NetworkParams
     */
    bytes?: any;
    /**
     * 
     * @type {number}
     * @memberof NetworkParams
     */
    bytesPerSecond?: any;
    /**
     * 
     * @type {number}
     * @memberof NetworkParams
     */
    dropped?: any;
    /**
     * 
     * @type {number}
     * @memberof NetworkParams
     */
    droppedPerSecond?: any;
    /**
     * 
     * @type {number}
     * @memberof NetworkParams
     */
    errors?: any;
    /**
     * 
     * @type {number}
     * @memberof NetworkParams
     */
    errorsPerSecond?: any;
    /**
     * 
     * @type {number}
     * @memberof NetworkParams
     */
    packets?: any;
    /**
     * 
     * @type {number}
     * @memberof NetworkParams
     */
    packetsPerSecond?: any;
}
