/* tslint:disable */
/* eslint-disable */
/**
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ParticipantBody
 */
export interface ParticipantBody {
    /**
     * 
     * @type {string}
     * @memberof ParticipantBody
     */
    audioFeed?: any;
    /**
     * 
     * @type {string}
     * @memberof ParticipantBody
     */
    browser: any;
    /**
     * normalize indentaion
     * @type {string}
     * @memberof ParticipantBody
     */
    computeUnit?: any;
    /**
     * 
     * @type {number}
     * @memberof ParticipantBody
     */
    count: any;
    /**
     * 
     * @type {Date}
     * @memberof ParticipantBody
     */
    created?: any;
    /**
     * 
     * @type {number}
     * @memberof ParticipantBody
     */
    groupId?: any;
    /**
     * 
     * @type {number}
     * @memberof ParticipantBody
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof ParticipantBody
     */
    location?: any;
    /**
     * 
     * @type {string}
     * @memberof ParticipantBody
     */
    mediaType?: any;
    /**
     * 
     * @type {string}
     * @memberof ParticipantBody
     */
    name: any;
    /**
     * 
     * @type {string}
     * @memberof ParticipantBody
     */
    network?: any;
    /**
     * 
     * @type {number}
     * @memberof ParticipantBody
     */
    profileId?: any;
    /**
     * 
     * @type {boolean}
     * @memberof ParticipantBody
     */
    recordAudio?: any;
    /**
     * 
     * @type {number}
     * @memberof ParticipantBody
     */
    testId?: any;
    /**
     * 
     * @type {Date}
     * @memberof ParticipantBody
     */
    updated?: any;
    /**
     * 
     * @type {string}
     * @memberof ParticipantBody
     */
    videoFeed?: any;
}
