/* tslint:disable */
/* eslint-disable */
/**
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PaymentMethod
 */
export interface PaymentMethod {
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    brand?: any;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    cardholderName?: any;
    /**
     * 
     * @type {number}
     * @memberof PaymentMethod
     */
    expMonth?: any;
    /**
     * 
     * @type {number}
     * @memberof PaymentMethod
     */
    expYear?: any;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    id?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PaymentMethod
     */
    isDefault?: any;
    /**
     * 
     * @type {string}
     * @memberof PaymentMethod
     */
    last4?: any;
}
