/* tslint:disable */
/* eslint-disable */
/**
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    accountRole?: any;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    awsInfoId?: any;
    /**
     * 
     * @type {Date}
     * @memberof Project
     */
    created?: any;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    language: any;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    memberCount?: any;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    name: any;
    /**
     * 
     * @type {number}
     * @memberof Project
     */
    subscriptionId?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Project
     */
    trialExpired?: any;
    /**
     * 
     * @type {Date}
     * @memberof Project
     */
    updated?: any;
}
