/* tslint:disable */
/* eslint-disable */
/**
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Run
 */
export interface Run {
    /**
     * 
     * @type {Date}
     * @memberof Run
     */
    created?: any;
    /**
     * 
     * @type {Date}
     * @memberof Run
     */
    executionFinished?: any;
    /**
     * 
     * @type {Date}
     * @memberof Run
     */
    executionStarted?: any;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    groupCount?: any;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    incrementStrategy?: any;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    launchingAccountId?: any;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    participantTimeout?: any;
    /**
     * 
     * @type {Date}
     * @memberof Run
     */
    processingFinished?: any;
    /**
     * 
     * @type {Date}
     * @memberof Run
     */
    processingStarted?: any;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    scriptFileId?: any;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    startInterval?: any;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    status?: any;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    successRate?: any;
    /**
     * 
     * @type {number}
     * @memberof Run
     */
    testId?: any;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    testMode?: any;
    /**
     * 
     * @type {string}
     * @memberof Run
     */
    testName?: any;
    /**
     * 
     * @type {Date}
     * @memberof Run
     */
    updated?: any;
}
