/* tslint:disable */
/* eslint-disable */
/**
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * Subscription describes single subscription instance with JSON field descriptions.
 * @export
 * @interface Subscription
 */
export interface Subscription {
    /**
     * 
     * @type {Date}
     * @memberof Subscription
     */
    activationDate?: any;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    billingEmail: any;
    /**
     * 
     * @type {Date}
     * @memberof Subscription
     */
    created?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Subscription
     */
    earlySubscriber?: any;
    /**
     * 
     * @type {number}
     * @memberof Subscription
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    paymentPlan: any;
    /**
     * 
     * @type {string}
     * @memberof Subscription
     */
    paymentStatus?: any;
    /**
     * 
     * @type {Date}
     * @memberof Subscription
     */
    updated?: any;
}
