/* tslint:disable */
/* eslint-disable */
/**
 * Loadero Controller
 * This application serves main Loadero's endpoints that can be used to manipulate test data and other services
 *
 * OpenAPI spec version: v0.32.1
 * Contact: support@loadero.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Test
 */
export interface Test {
    /**
     * 
     * @type {Date}
     * @memberof Test
     */
    created?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Test
     */
    deleted?: any;
    /**
     * 
     * @type {number}
     * @memberof Test
     */
    groupCount?: any;
    /**
     * 
     * @type {number}
     * @memberof Test
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    incrementStrategy: any;
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    mode: any;
    /**
     * 
     * @type {string}
     * @memberof Test
     */
    name: any;
    /**
     * 
     * @type {number}
     * @memberof Test
     */
    participantCount?: any;
    /**
     * 
     * @type {number}
     * @memberof Test
     */
    participantTimeout: any;
    /**
     * 
     * @type {number}
     * @memberof Test
     */
    projectId?: any;
    /**
     * 
     * @type {number}
     * @memberof Test
     */
    scriptFileId?: any;
    /**
     * 
     * @type {number}
     * @memberof Test
     */
    startInterval: any;
    /**
     * 
     * @type {Date}
     * @memberof Test
     */
    updated?: any;
}
